services:
  uptime:
    image: louislam/uptime-kuma:1
    volumes:
      - kuma_data:/app/data
    ports:
      - "3001:3001"
    restart: always
    container_name: uptime
    networks:
      - uptime_bridge

volumes:
  kuma_data:
networks:
  uptime_bridge:
    external: true
