services:
  file-server:
    image: nginx:alpine
    volumes:
      - static_content:/var/www/servers/cansu.dev/static/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./logs:/var/log/nginx
      - ./htpasswd:/etc/nginx/htpasswd:ro
      - ./setup.sh:/docker-entrypoint.d/50-setup.sh
    ports:
      - "44444:80"
    restart: unless-stopped
    networks:
      - uptime_bridge

volumes:
  static_content:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /var/www/servers/cansu.dev/static/

networks:
  uptime_bridge:
    external: true
