services:
  file-server:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./fancyindex:/var/www/servers/cansu.dev/static/fancyindex:ro
      - static_content:/var/www/servers/cansu.dev/static/
    user: 1337:1337 
    ports:
      - "44444:80"
    restart: unless-stopped
    networks:
      - uptime_bridge

volumes:
  static_content:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /var/www/servers/cansu.dev/static/

networks:
  uptime_bridge:
    external: true
