services:
  file-server:
    image: debian:sid-slim
    command: /usr/sbin/lighttpd -D -f /etc/lighttpd/lighttpd.conf
    volumes:
      - static_content:/var/www/servers/cansu.dev/static/
      - ./lighttpd.conf:/etc/lighttpd/lighttpd.conf:ro
      - ./logs:/var/log/lighttpd
    ports:
      - "44444:80"
    restart: unless-stopped
    init: true
    entrypoint: |
      /bin/sh -c "
        export DEBIAN_FRONTEND=noninteractive
        apt-get update && apt-get install -o Dpkg::Options::=--force-confdef -y lighttpd
        
        getent group static_cansu_dev_group || groupadd static_cansu_dev_group
        getent passwd static_cansu_dev_user || useradd -r -g static_cansu_dev_group -d /var/www/servers/cansu.dev/static/ -s /usr/sbin/nologin static_cansu_dev_user
        
        mkdir -p /var/log/lighttpd
        chown -R static_cansu_dev_user:static_cansu_dev_group /var/log/lighttpd
        chmod -R 755 /var/log/lighttpd

        chown -R static_cansu_dev_user:static_cansu_dev_group /var/www/servers/cansu.dev/static/
        chmod -R 755 /var/www/servers/cansu.dev/static/
        
        touch /etc/lighttpd/lighttpd-htpasswd
        
        exec $0 $@
      "

volumes:
  static_content:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /var/www/servers/cansu.dev/static/
