name: cansu-dev-dj-backend

services:
  golang:
    cap_add:
      - SYS_ADMIN
    build:
      context: ~/cansu.dev/dj/backend
      dockerfile: Dockerfile
    environment:
      - POSTGRESQL_USERNAME=${POSTGRESQL_USERNAME}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRESQL_DB=${POSTGRESQL_DB}
      - S3_ACCOUNT_ID=${S3_ACCOUNT_ID}
      - S3_ACCESS_KEY_ID=${S3_ACCESS_KEY_ID}
      - S3_ACCESS_KEY_SECRET=${S3_ACCESS_KEY_SECRET}
      - UPLOAD_ADMIN_USERNAME=${UPLOAD_ADMIN_USERNAME}
      - UPLOAD_ADMIN_PASSWORD=${UPLOAD_ADMIN_PASSWORD}
      - PORT=${CANSU_DEV_DJ_API_PORT}
    networks:
      - cansu_dev_dj_backend_bridge
      - cansu_dev_code_judge0_bridge
    ports:
      - "8000:8000"
    volumes:
      - /lib/modules:/lib/modules


networks:
  cansu_dev_dj_backend_bridge:
    external: true
  cansu_dev_code_judge0_bridge:
    external: true