version: "3.8"
services:
  pg-primary:
    image: postgres:16
    volumes:
      - pg_primary_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRESQL_DB}
      POSTGRES_USER: ${POSTGRESQL_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
      POSTGRES_REPLICATION_USER: ${REPMGR_USERNAME}
      POSTGRES_REPLICATION_PASSWORD: ${REPMGR_PASSWORD}
    ports:
      - "5432:5432" #expose primary port for pgbouncer
    command:
      [
        "-c",
        "wal_level=replica",
        "-c",
        "max_wal_senders=10",
        "-c",
        "max_replication_slots=10",
      ]
    networks:
      - database_bridge

  pg-replica:
    image: postgres:16
    volumes:
      - pg_replica_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRESQL_DB}
      POSTGRES_USER: ${POSTGRESQL_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
      PGDATA: /var/lib/postgresql/data
    command:
      [
        "-c",
        "primary_conninfo=host=pg-primary port=5432 user=${REPMGR_USERNAME} password=${REPMGR_PASSWORD} application_name=pg_replica",
      ]
    depends_on:
      - pg-primary
    networks:
      - database_bridge

  pgbouncer:
    image: edoburu/pgbouncer:latest
    ports:
      - 6432:6432
    volumes:
      - ./pgbouncer.ini:/etc/pgbouncer/pgbouncer.ini
      - ./userlist.txt:/pgbouncer/userlist.txt
    environment:
      - DB_HOST=pg-primary
      - DB_USER=${POSTGRESQL_USERNAME}
      - DB_PASSWORD=${POSTGRESQL_PASSWORD}
    networks:
      - database_bridge
    depends_on:
      - pg-primary

networks:
  database_bridge:
    external: true

volumes:
  pg_primary_data:
  pg_replica_data:
