version: "3.8"

x-postgres-common: &postgres-common
  POSTGRES_DB: ${POSTGRESQL_DB}
  POSTGRES_USER: ${POSTGRESQL_USERNAME}
  POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
  REPLICATION_MODE: replica
  REPLICATION_USER: ${REPMGR_USER}
  REPLICATION_PASSWORD: ${REPMGR_PASSWORD}

services:
  pg-primary:
    image: docker.io/bitnami/postgresql:16
    volumes:
      - pg_primary_data:/bitnami/postgresql/data
    environment:
      <<: *postgres-common
      REPLICATION_MODE: master
    networks:
      - database_network

  pg-replica:
    image: docker.io/bitnami/postgresql:16
    volumes:
      - pg_replica_data:/bitnami/postgresql/data
    environment:
      <<: *postgres-common
      REPLICATION_PRIMARY_HOST: pg-primary
    depends_on:
      - pg-primary
    networks:
      - database_network

  pgbouncer:
    image: edoburu/pgbouncer:latest
    ports:
      - 6432:6432
    volumes:
      - ./pgbouncer.ini:/etc/pgbouncer/pgbouncer.ini
      - ./userlist.txt:/etc/pgbouncer/userlist.txt
    environment:
      - DB_HOST=pg-primary
      - DB_USER=${POSTGRESQL_USERNAME}
      - DB_PASSWORD=${POSTGRESQL_PASSWORD}
    networks:
      - database_network
    depends_on:
      - pg-primary
      - pg-replica

networks:
  database_network:
    driver: bridge

volumes:
  pg_primary_data:
  pg_replica_data:
