name: databases-redis
services:
  dragonfly:
        image: 'docker.dragonflydb.io/dragonflydb/dragonfly'
        restart: always
        environment:
          - REDIS_PASSWORD=${REDIS_PASSWORD}
        command: dragonfly --requirepass ${REDIS_PASSWORD}
        ulimits:
          memlock: -1
        ports:
          - "6379:6379"
        volumes:
          - dragonflydata:/data
        networks:
          - cansu_dev_dj_backend_bridge
          - cansu_dev_code_judge0_bridge
  redis-commander:
        image: ghcr.io/joeferner/redis-commander:latest
        restart: always
        environment:
          - REDIS_PORT=6379
          - REDIS_HOST=dragonfly
          - REDIS_PASSWORD=${REDIS_PASSWORD}
        ports:
          - "8081:8081"
        user: redis
        networks:
          - cansu_dev_dj_backend_bridge
        depends_on:
          - dragonfly

networks:
  cansu_dev_dj_backend_bridge:
    external: true
  cansu_dev_code_judge0_bridge:
    external: true

volumes:
  dragonflydata: